POST http://localhost:3000/api/chatbot/order HTTP/1.1
content-type: application/json

{
  "userPhone": 1234567890,
  "orderItems": [
    {
      "productId": 1,
      "units": 2,
      "unitType": "KG"
    },
    {
      "productId": 2,
      "units": 1,
      "unitType": "PZ"
    }
  ]
}